//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.WPF
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Appointment
    //{
    //    public System.Guid AppointmentID { get; set; }
    //    public System.DateTime Date { get; set; }
    //    public Nullable<System.Guid> DoctorID { get; set; }
    //    public Nullable<int> Duration { get; set; }
    //}
}
