//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorPatient
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DoctorID { get; set; }
        public Nullable<System.Guid> PatientID { get; set; }
    }
}
