//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmployeeID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
    }
}
