//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.WPF
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Patient
    //{
    //    public System.Guid PatientID { get; set; }
    //    public string Name { get; set; }
    //    public Nullable<System.DateTime> BirthDate { get; set; }
    //    public string Address { get; set; }
    //    public string Diagnosis { get; set; }
    //}
}
