//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public System.Guid RoomID { get; set; }
        public int RoomNumber { get; set; }
        public string RoomType { get; set; }
    }
}
